-- 1. Create the table for tracking price sheet conversions
create table price_sheets (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  filename text,
  image_url text,
  excel_url text,
  status text
);

-- 2. Storage Bucket Setup (Manual Step)
-- Go to Storage -> New Bucket -> Name: 'price-sheets' -> Check 'Public bucket'
